language: c

compiler:
  - gcc

matrix:
  include:
  - python: "2.7"
    os: linux
  - python: "2.7"
    os: osx
  - python: "2.6"
    os: osx
  - python: "2.5"
    os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pip; pip install wheel; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; sudo apt-get install -qq python-pip; sudo pip install wheel; fi

script:
# Build C lib
  - ./autogen.sh
  - ./configure
  - make

# Run main librxvm test suite
  - make check

# Build python extension and run tests
  - python setup.py build
  - python setup.py bdist_wheel
  - sudo pip install . --upgrade
  - python pyrxvm/test/test.py

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: pyrxvm/dist/*
  api-key: $GITHUB_TOKEN
  on:
    repo: eriknyquist/librxvm
    tags: true
