REGEXC_NAME := regexc
REGEXC_C_SRCS := $(wildcard src/*.c)
REGEXC_OBJS := ${REGEXC_C_SRCS:.c=.o}
REGEXC_INCLUDE_DIR := include

MAX_CHARC_LEN := 512
MAX_NEST_PARENS := 512

OPTS := \
MAX_CHARC_LEN=$(MAX_CHARC_LEN) \
MAX_NEST_PARENS=$(MAX_NEST_PARENS)

MACROS := $(addprefix -D , $(OPTS))
CFLAGS := -Wall -g -I$(REGEXC_INCLUDE_DIR) $(MACROS)

$(REGEXC_NAME): $(REGEXC_OBJS)
	$(CC) $(REGEXC_OBJS) -o $(REGEXC_NAME) -I$(REGEXC_INCLUDE_DIR)


clean:
	@- $(RM) $(REGEXC_NAME)
	@- $(RM) $(REGEXC_OBJS)

distclean: clean
