#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "rxvm.h"
#include "test_common.h"
#include "lfix_to_str.h"

static int tests;
static const char *func;

static void log_trs (char *msg)
{
    fprintf(trsfp, ":test-result: %s %s #%d\n", msg, func, tests);
}

void verify_rxvm_lfix_to_str (char *regex, char *lfix)
{
    char *msg;
    int ret;
    rxvm_t compiled;

    if ((ret = rxvm_compile(&compiled, regex)) < 0) {
        fprintf(logfp, "Failed to compile expression %s\n", regex);
        log_trs("FAIL");
        return;
    }

    if ((compiled.lfix == NULL && lfix != NULL) ||
        (compiled.lfix && strcmp(compiled.lfix, lfix) != 0)) {

        fprintf(logfp, "\nFail: Incorrect longest-fixed-string "
                       "generated by lfix_to_str, for expression:\n%s\n\n",
                       regex);
        fprintf(logfp, "expected:\n\t%s\n\n", lfix);
        fprintf(logfp, "seen:\n\t%s\n\n",
                       (compiled.lfix) ? compiled.lfix : "(NULL)");
        msg = "FAIL";
    } else {
        msg = "PASS";
    }

    rxvm_free(&compiled);
    log_trs(msg);
    printf("%s: %s #%i\n", msg, func, ++tests);
}

void test_rxvm_lfix_to_str (void)
{
    tests = 0;
    func = __func__;

    verify_rxvm_lfix_to_str("AaBb+", "AaBb");
    verify_rxvm_lfix_to_str("ab+c", "ab");
    verify_rxvm_lfix_to_str("abc?d", "ab");
    verify_rxvm_lfix_to_str("ab*c", NULL);

    verify_rxvm_lfix_to_str("abcd{,5}c", "abc");
    verify_rxvm_lfix_to_str("abcd{0,}c", "abc");
    verify_rxvm_lfix_to_str("abcd{1,}c", "abcd");
    verify_rxvm_lfix_to_str("ab{123,}", "ab");
    verify_rxvm_lfix_to_str("ab{1234,}123", "123");

    verify_rxvm_lfix_to_str("abc(defg)", "abc");
    verify_rxvm_lfix_to_str("abc(defg)hijk", "hijk");

    verify_rxvm_lfix_to_str("abc(d|e)fghi", "fghi");
    verify_rxvm_lfix_to_str("abc(de)hij|k", NULL);
    verify_rxvm_lfix_to_str("aaaaa|bbbbb", NULL);
    verify_rxvm_lfix_to_str("aaa|bbb|ccc|ddd", NULL);
    verify_rxvm_lfix_to_str("aaa", "aaa");
    verify_rxvm_lfix_to_str("aa\\*", "aa*");
    verify_rxvm_lfix_to_str("aaa\\*b\\?b", "aaa*b?b");

    verify_rxvm_lfix_to_str("abc(def)+ijkl", "ijkl");
    verify_rxvm_lfix_to_str("abc(def)+ijkl*", "abc");
    verify_rxvm_lfix_to_str("abc(def)+ijklm*", "ijkl");
    verify_rxvm_lfix_to_str("abcc(def)+ijkl", "abcc");

    verify_rxvm_lfix_to_str("abc(d|(e?|f|g+)|h)ijkl", "ijkl");
    verify_rxvm_lfix_to_str("abc(d|(e?|f|g+)|h)ijkl*", "abc");
    verify_rxvm_lfix_to_str("abc(d|(e?|f|g+)|h)ijklm*", "ijkl");
    verify_rxvm_lfix_to_str("abcc(d|(e?|f|g+)|h)ijkl", "abcc");

    verify_rxvm_lfix_to_str("abcd*efghi", "efghi");
    verify_rxvm_lfix_to_str("abcd\nefghi", "abcd");
    verify_rxvm_lfix_to_str("abcd[ \t\n]efghi", "abcd");
    verify_rxvm_lfix_to_str("abcd[ \t]efghi", "efghi");
    verify_rxvm_lfix_to_str("abcd(ef\n)?efghi", "abcd");
    verify_rxvm_lfix_to_str("abcc(d|(e?|f|g+)|h)ijklm", "ijklm");
    verify_rxvm_lfix_to_str("abcc(d|(e?|f\n|g+)|h)ijklm", "abcc");

    verify_rxvm_lfix_to_str("ab\\*\nefghi", "ab*");
    verify_rxvm_lfix_to_str("ab\\*\n(e|fg)hi", "ab*");
    verify_rxvm_lfix_to_str("ab\\*\\+\\?\nefghi", "ab*+?");
    verify_rxvm_lfix_to_str("abc(def)*ghi\\+", "ghi+");

    verify_rxvm_lfix_to_str("abc[defgh]", "abc");
    verify_rxvm_lfix_to_str("abc[defgh]ijkl", "ijkl");
    verify_rxvm_lfix_to_str("abc[d\\]fgh]ijkl", "ijkl");
    verify_rxvm_lfix_to_str("abc[d\\]fgh]ij\\kl", "ijkl");

    verify_rxvm_lfix_to_str("abcd+efgh", "abcd");
}
